### ISSUE TITLE
Source: ACS

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-community-profiles#1]
## To-do: 
- [x] get variable mapping based on [schema](https://communityprofiles.planning.nyc.gov/data/cd_profile_data_dictionary.csv), seems like we already have parts of it  --> [possible field mappings](https://nyco365.sharepoint.com/sites/NYCPLANNING/pc/_layouts/15/Doc.aspx?sourcedoc=%7B559BD7E6-F4FD-41C0-BC5A-378D1C8F719C%7D&file=community_district_profiles_v201903.xlsm&action=default&mobileredirect=true&cid=3e54b864-197f-4cc8-b093-e9f376378c74)
  - we would need the following info: 
    1. what is the variable (e.g. pop_1)
    2. do we want MOE:m, Estimation:e, Percentage Estimation:p, Percentage Estimation MOE:z?
    3. which category the variable falls under (housing, demographics, economics or social)

- [x] write query to pull these variables from the PFF database
- [x] need instruction on `pct_other_nh`, is it field `OthNH` in pff? 

<details>
<summary>mapping</summary>

Community profiles fields | PFF fields
-- | --
puma | GeoID
borocd | GeogName
female_50_54 | FPop50t54P
moe_under18_rate_nyc | PopU181Z
moe_under18_rate_boro | PopU181Z
pop_acs | Pop_1E
pct_hispanic | Hsp1P
pct_other_nh | Field may exist in PFF
pct_asian_nh | AsnNHP
pct_black_nh | BlNHP
pct_white_nh | WtNHP
female_85_over | FPop85plP
male_85_over | MPop85plP
female_80_84 | FPop80t84P
male_80_84 | MPop80t84P
female_75_79 | FPop75t79P
male_75_79 | MPop75t79P
female_70_74 | FPop70t74P
male_70_74 | MPop70t74P
female_65_69 | FPop65t69P
male_65_69 | MPop65t69P
female_60_64 | FPop60t64P
male_60_64 | MPop60t64P
female_55_59 | FPop55t59P
male_55_59 | MPop55t59P
male_50_54 | MPop50t54P
female_45_49 | FPop45t49P
male_45_49 | MPop45t49P
female_40_44 | FPop40t44P
male_40_44 | MPop40t44P
female_35_39 | FPop35t39P
male_35_39 | MPop35t39P
female_30_34 | FPop30t34P
male_30_34 | MPop30t34P
female_25_29 | FPop25t29P
male_25_29 | MPop25t29P
female_20_24 | FPop20t24P
male_20_24 | MPop20t24P
female_15_19 | FPop15t19P
male_15_19 | MPop15t19P
female_10_14 | FPop10t14P
male_10_14 | MPop10t14P
female_5_9 | FPop5t9P
male_5_9 | MPop5t9P
female_under_5 | FPop0t5P
male_under_5 | MPop0t5P
moe_over65_rate_nyc | Pop65pl1Z
over65_rate_nyc | Pop65pl1P
moe_over65_rate_boro | Pop65pl1Z
over65_rate_boro | Pop65pl1P
moe_over65_rate | Pop65pl1Z
over65_rate | Pop65pl1P
under18_rate_nyc | PopU181P
under18_rate_boro | PopU181P
moe_under18_rate | PopU181Z
under18_rate | PopU181P
moe_lep_rate_nyc | LgOEnLEP1Z
lep_rate_nyc | LgOEnLEP1P
moe_lep_rate_boro | LgOEnLEP1Z
lep_rate_boro | LgOEnLEP1P
moe_lep_rate | LgOEnLEP1Z
lep_rate | LgOEnLEP1P
moe_foreign_born | Fb1Z
pct_foreign_born | Fb1P
moe_hh_rent_burd_nyc | GRPI35plZ
pct_hh_rent_burd_nyc | GRPI35plP
moe_hh_rent_burd_boro | GRPI35plZ
pct_hh_rent_burd_boro | GRPI35plP
moe_hh_rent_burd | GRPI35plZ
pct_hh_rent_burd | GRPI35plP
moe_mean_commute_nyc | MnTrvTmM
mean_commute_nyc | MnTrvTmE
moe_mean_commute_boro | MnTrvTmM
mean_commute_boro | MnTrvTmE
moe_mean_commute | MnTrvTmM
mean_commute | MnTrvTmE
moe_unemployment_nyc | CvLFUEm1Z
unemployment_nyc | CvLFUEm1P
moe_unemployment_boro | CvLFUEm1Z
unemployment_boro | CvLFUEm1P
moe_unemployment | CvLFUEm1Z
unemployment | CvLFUEm1P
moe_bach_deg_nyc | EA_BchDHZ
pct_bach_deg_nyc | EA_BchDHP
moe_bach_deg_boro | EA_BchDHZ
pct_bach_deg_boro | EA_BchDHP
moe_bach_deg | EA_BchDHZ
pct_bach_deg | EA_BchDHP

</details>

## Resources:
wiki: https://github.com/NYCPlanning/db-community-profiles/wiki/census-Indicators

**Comment by AmandaDoyle** [comment]
I asked PC to do the field mapping here
https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7B39d56477-afc2-410d-a43c-66165b22bc0e%7D&action=editnew

**Comment by SPTKL** [comment]
what to do with multiple community districts in 1 PUMA?
e.g.
PUMA2010 | NYC-Bronx Community District 3 & 6--Belmont, Crotona Park East & East Tremont PUMA | 3705 
-- | -- | --

**Comment by SPTKL** [comment]
NYCPlanning/db-community-profiles/issues/43
